### ISSUE TITLE
Waiting for confirmation email

### ISSUE THREAD

**Issue by Skbindas** [im-hanzou/blockmesh-autoref#12]
Registration successful but waiting for email confirmation showing 

Error Max try reach no email found 
Error no email receive or inbox expire
![IMG_20241226_073922](https://github.com/user-attachments/assets/c97efedf-7395-4cf6-b015-3b2fbb68772a)
![IMG_20241226_073922](https://github.com/user-attachments/assets/7a0961e4-d86a-4d34-90eb-4c8e3c8e643e)

**Comment by im-hanzou** [comment]
blockmesh is updating mechanism, 
this script update is still pending, it will be developed again soon
