### ISSUE TITLE
ERROR → No emails received or inbox expired

### ISSUE THREAD

**Issue by yudhistirank** [im-hanzou/blockmesh-autoref#3]
how to solve "ERROR → No emails received or inbox expired" ?

![Screenshot 2024-11-18 081542](https://github.com/user-attachments/assets/562bad95-6d4d-4872-885b-7a234ab616f1)

![Screenshot 2024-11-18 081744](https://github.com/user-attachments/assets/0436956d-b8ea-4d0b-aa3b-7b5212a11fa3)

**Comment by im-hanzou** [comment]
Please check #2
