### ISSUE TITLE
?

### ISSUE THREAD

**Issue by CryptoAirdropHindi1** [im-hanzou/blockmesh-autoref#4]
![Screenshot 2024-11-18 125450](https://github.com/user-attachments/assets/5c94631e-5b84-4539-8ab9-3dfcd9759eb7)

**Comment by CryptoAirdropHindi1** [comment]
![Screenshot 2024-11-18 153149](https://github.com/user-attachments/assets/b6590c92-5658-48ab-a2f8-688fb626d627)

**Comment by im-hanzou** [comment]
please read, sometime blockmesh smtp server and sometime alive. i dont know they are doing #2
