### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by professordevil25** [im-hanzou/blockmesh-autoref#5]
![image](https://github.com/user-attachments/assets/1ab2b9c6-f5d8-46d6-9080-48d991b63574)

**Comment by im-hanzou** [comment]
this is problem with your proxy

**Comment by professordevil25** [comment]
> this is problem with your proxy

i change the ip but same as show

**Comment by im-hanzou** [comment]
> > this is problem with your proxy
> 
> i change the ip but same as show

yes blockmesh smtp server down sometimes, check this #2
