### ISSUE TITLE
Update pls

### ISSUE THREAD

**Issue by T7890u** [im-hanzou/blockmesh-autoref#6]

**Comment by im-hanzou** [comment]
i will, just wait k

**Comment by im-hanzou** [comment]
#2

**Comment by T7890u** [comment]
![Uploading Screenshot_20241120_064819_UserLAnd.jpg…]()

Is this okke?

**Comment by im-hanzou** [comment]
i cant see your screenshot

**Comment by T7890u** [comment]
> i cant see your screenshot

![Screenshot_20241120_064819_UserLAnd](https://github.com/user-attachments/assets/ad8841fa-bfad-4a81-a5e1-dc35a3011e56)
