### ISSUE TITLE
nodepay multibypass not working brother

### ISSUE THREAD

**Issue by professordevil25** [im-hanzou/blockmesh-autoref#8]

**Comment by im-hanzou** [comment]
can you show the proof error

**Comment by professordevil25** [comment]
![image](https://github.com/user-attachments/assets/3e430954-9548-4b5e-be62-ea872422e556)
 i run this almost 1 hour ago

**Comment by im-hanzou** [comment]
are you pasted many tokens and proxies?

**Comment by professordevil25** [comment]
> are you pasted many tokens and proxies?

yes.
![image](https://github.com/user-attachments/assets/81a49df5-2c85-4b27-afe9-a95867db53d4)
![image](https://github.com/user-attachments/assets/4f4b7115-c1e7-471a-b917-0bfa3f91990f)

**Comment by im-hanzou** [comment]
did you try with 4 tokens with 40proxies?

**Comment by professordevil25** [comment]
> did you try with 4 tokens with 40proxies?

4 token with 50 proxy

**Comment by professordevil25** [comment]
> did you try with 4 tokens with 40proxies?

thanks brother.i found my problem.

**Comment by professordevil25** [comment]
> did you try with 4 tokens with 40proxies?

can you turn on every error option in your  bot? its help us to contact you

**Comment by im-hanzou** [comment]
yes, i already update the script
